import os
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from fastapi import HTTPException

class CryptoEngine:
    def __init__(self, hex_key: str):
        """Initializes the engine with a 256-bit key represented in hex."""
        try:
            self.key = bytes.fromhex(hex_key)
            if len(self.key) != 32:
                raise ValueError("Key must be exactly 32 bytes (256 bits).")
            self.aesgcm = AESGCM(self.key)
        except Exception as e:
            raise RuntimeError(f"Failed to initialize Crypto Engine: {str(e)}")

    def encrypt_data(self, plain_text: str) -> str:
        """
        Encrypts a string using AES-256-GCM.
        Returns a hex string containing the nonce concatenated with the ciphertext.
        """
        if not plain_text:
            return plain_text
            
        # Generate a secure 12-byte random nonce for GCM
        nonce = os.urandom(12)
        data_bytes = plain_text.encode('utf-8')
        
        # Encrypt data
        ciphertext = self.aesgcm.encrypt(nonce, data_bytes, None)
        
        # Combine nonce and ciphertext so we can decode it later, then store as hex
        return (nonce + ciphertext).hex()

    def decrypt_data(self, hex_cipher_text: str) -> str:
        """
        Decrypts a hex string generated by encrypt_data.
        Raises an error if the data has been tampered with.
        """
        if not hex_cipher_text:
            return hex_cipher_text
            
        try:
            raw_bytes = bytes.fromhex(hex_cipher_text)
            if len(raw_bytes) < 12:
                raise ValueError("Ciphertext is too short to contain a valid nonce.")
                
            # Extract the 12-byte nonce from the beginning
            nonce = raw_bytes[:12]
            ciphertext = raw_bytes[12:]
            
            # Decrypt data (GCM automatically verifies integrity)
            decrypted_bytes = self.aesgcm.decrypt(nonce, ciphertext, None)
            return decrypted_bytes.decode('utf-8')
        except Exception:
            # If the database data was manipulated, GCM validation fails immediately
            raise HTTPException(status_code=400, detail="Data tampering detected during decryption.")
